### ISSUE TITLE
Has anything changed with Alfred 5? I've updated, but now the workflow isn't working anymore. 

### ISSUE THREAD

**Issue by mvaneijgen** [wrjlewis/notion-search-alfred-workflow#48]
First I thought it was my cookie, because it is doing the same as when the cookie has elapsed, aka it shows me to search on google.

This is what I see in the debugger. 
```
[09:15:56.301] Logging Started...
[09:16:01.070] Notion Search[Script Filter] Queuing argument ''
[09:16:01.390] Notion Search[Script Filter] Script with argv '(null)' finished
[09:16:01.393] ERROR: Notion Search[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/m/Dropbox/Documents/_assets/Alfred/Alfred.alfredpreferences/workflows/user.workflow.1EA56472-26A4-41CF-8638-BF1E7FDD254B/notion.py", line 190, in <module>
    conn.request("POST", "/api/v3/getRecentPageVisits",
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1276, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1322, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1271, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1031, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 969, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1448, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 512, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1070, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1341, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
```

**Comment by wrjlewis** [comment]
Hi

If you installed Python 3 yourself (instead of letting macOS do it for you) you may need to install the certificates yourself too.

https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate/58525755#58525755

^ give this a go

**Comment by mvaneijgen** [comment]
Weird never had that issue before, but that was it! Thanks!

**Comment by wrjlewis** [comment]
Awesome! Glad it's working
